{
 "title": "Default Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "SessionName", "query": { "query": "label_values(SessionName)" } },
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Scheduler Task State",
   "type": "graph",
   "description": "Current number of tasks in a particular state.\n\nState: the task state, as described by rpc::TaskState proto in common.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(ray_tasks{State=~\"FINISHED|FAILED\",SessionName=\"$SessionName\"}[14d])) by (State) or clamp_min(sum(ray_tasks{State!~\"FINISHED|FAILED\",SessionName=\"$SessionName\"}) by (State), 0)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Active Tasks by Name",
   "type": "graph",
   "description": "Current number of (live) tasks with a particular name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_tasks{State!~\"FINISHED|FAILED\",SessionName=\"$SessionName\"}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Scheduler Actor State",
   "type": "graph",
   "description": "Current number of actors in a particular state.\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{SessionName=\"$SessionName\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Active Actors by Name",
   "type": "graph",
   "description": "Current number of (live) actors with a particular name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{State!=\"DEAD\",SessionName=\"$SessionName\"}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Scheduler CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors.\n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"CPU\",State=\"USED\",SessionName=\"$SessionName\"}) by (instance)",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\",SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Object store memory usage by location. The dotted line indicates the object store memory capacity.\n\nLocation: where the memory was allocated, which is MMAP_SHM or MMAP_DISK to indicate memory-mapped page, SPILLED to indicate spillage to disk, and WORKER_HEAP for objects small enough to be inlined in worker memory. Refer to metric_defs.cc for more information.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{SessionName=\"$SessionName\"} / 1e9) by (Location)",
     "legendFormat": "{{Location}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",SessionName=\"$SessionName\"} / 1e9)",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_resources{Name=\"GPU\",State=\"USED\",SessionName=\"$SessionName\"}",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\",SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler Placement Groups",
   "type": "graph",
   "description": "Current number of placement groups in a particular state.\n\nState: the placement group state, as described by the rpc::PlacementGroupTable proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "placement groups" }
   ],
   "targets": [
    {
     "expr": "sum(ray_placement_groups{SessionName=\"$SessionName\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Node CPU (hardware utilization)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\",SessionName=\"$SessionName\"} * ray_node_cpu_count{instance=~\"$Instance\",SessionName=\"$SessionName\"} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU (hardware utilization)",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\",SessionName=\"$SessionName\"} / 100",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_disk_free{SessionName=\"$SessionName\"}) + sum(ray_node_disk_usage{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk IO Speed",
   "type": "graph",
   "description": "Disk IO per node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_io_write_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "ray_node_disk_io_read_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (heap + object store)",
   "type": "graph",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_mem_total{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory by Component",
   "type": "graph",
   "description": "The physical (hardware) memory usage across the cluster, broken down by component. This reports the summed USS (unique set size) per Ray component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_uss_mb{SessionName=\"$SessionName\"} * 1e6) by (Component)",
     "legendFormat": "{{Component}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\",SessionName=\"$SessionName\"} * 1024 * 1024",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{SessionName=\"$SessionName\"}) + sum(ray_node_gram_used{SessionName=\"$SessionName\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "graph",
   "description": "Network speed per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "A total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_cluster_active_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Active Nodes: {{node_type}}"
    },
    {
     "expr": "sum(ray_cluster_failed_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Failed Nodes: {{node_type}}"
    },
    {
     "expr": "sum(ray_cluster_pending_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Pending Nodes: {{node_type}}"
    }
   ]
  }
 ]
}